# Generated by Django 4.0.5 on 2022-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
