# Generated by Django 4.0.5 on 2022-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_turnament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnament',
            name='type',
            field=models.IntegerField(choices=[(1, 'liga group'), (2, 'table group')], default=1),
        ),
    ]
