# Generated by Django 4.0.5 on 2022-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_turnament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnament',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
