# Generated by Django 4.0.5 on 2022-06-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_turnament_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
