# Generated by Django 4.0.5 on 2022-06-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_team_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerteam',
            name='PTS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
