# Generated by Django 4.0.5 on 2022-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_registerteam_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
