# Generated by Django 4.0.1 on 2022-07-04 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_team_groups_alter_team_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1r', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turnament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.turnament')),
            ],
        ),
    ]
