# Generated by Django 4.0.1 on 2022-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_roundevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundevent',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
