# Generated by Django 4.0.1 on 2022-07-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_roundevent_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundevent',
            name='point_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundevent',
            name='point_2',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
